export const Errors = {
  INVALID_LOGIN: 'Usuário e/ou senha inválidos',
  UNEXPECTED: 'Erro inesperado',
  INVALID_TOKEN: 'Token Inválido!',
  EXPIRED_TOKEN: 'Token expirado! Solicite uma nova recuperação de senha!',
  TOKEN_NOT_FOUND: 'Token não informado!',
  UNAUTHORIZED: 'Você não tem permissão para realizar essa ação',
  OBJECT_NOT_FOUND: 'Entidade não encontrada',
  ID_NOT_FOUND: 'O ID é obrigatório',
  USER_NOT_FOUND: 'Usuário não encontrado',
  USER_EMAIL_ALREADY_EXISTS: 'Já existe um usuário com o e-mail informado',
  USER_PHONE_ALREADY_EXISTS: 'Já existe um usuário com o telefone informado',
  USER_EMAIL_IS_REQUIRED: 'O email é obrigatório',
  FILE_UPLOAD_NOT_FOUND: 'Arquivo não encontrado',
  FILE_UPLOAD_ERROR: 'Falha no upload do arquivo',
  INVALID_FILE: 'Arquivo inválido',
  ROLE_ALREADY_EXISTS: 'Já existe um perfil de acesso com o nome informado',
  ROLE_NOT_FOUND: 'Perfil de acesso não encontrado',
  EMAIL_SENT: 'Email enviado',
  PERMISSION_NOT_FOUND: 'Permissão não encontrada',
  TOKEN_EXPIRED: 'Token expirado!',
  SETTINGS_NOT_FOUND: 'Configurações não encontrada',
  STATUS_NOT_FOUND: 'Status não encontrado',
  APPOINTMENT_DT_ALREADY_EXISTS:
    'Já existe um agendamento com esse documento de transporte',
  LOGS_NOT_FOUND: 'Log não encontrado',
  COMPANY_NOT_FOUND: 'Empresa não encontrada',
  COMPANY_NAME_ALREADY_EXISTS: 'Já existe uma empresa com esse nome',
  COMPANY_CNPJ_ALREADY_EXISTS: 'Já existe uma empresa com esse CNPJ',
  PASSWORD_REQUIRED: 'A senha não pode ser vazia',
  APPOINTMENT_NOT_FOUND: 'Agendamento não encontrado',
  COMPANY_PARAMETERS_NOT_FOUND: 'Parametrização da empresa não encontrada',
  COMPANY_PARAMETERS_ALREADY_EXISTS:
    'Já existe parametrização para essa empresa',
  SUBSIDIARY_NOT_FOUND: 'Filial não encontrada',
  VISITOR_NOT_FOUND: 'Visitante não encontrado',
  VISITOR_PROFILE_NOT_FOUND: 'Perfil de visitante não encontrado',
  DEPARTAMENT_NOT_FOUND: 'Departamento não encontrado',
  DEPARTMENT_ALREADY_EXISTS: 'Departamento já cadastrado',
  SUPPLIER_NOT_FOUND: 'Fornecedor não encontrado',
  SCHEDULE_DATE_IS_REQUIRED_FOR_ONE_TIME:
    'Data é obrigatória para agendamento único',
  VISITOR_NOT_FOUND_IN_APPOINTMENT: 'Visitante não encontrado no agendamento',
  SUBSIDIARY_ALREADY_EXISTS: 'Já existe uma filial com o nome infomado',
  DEVICE_NOT_FOUND: 'Dispositivo não encontrado',
  DEVICE_ALREADY_EXISTS: 'Já existe um dispositivo com o nome e IP informado',
  FACE_RECOGNITION_UPLOAD_FAILED: 'Falha no upload para reconhecimento facial',
  OCCUPATION_NOT_FOUND: 'Cargo não encontrado',
  OCCUPATION_ALREADY_EXISTS: 'Já existe um cargo com o nome informado',
  VENDOR_NOT_FOUND: 'Prestador não encontrado',
  VENDOR_INVITATION_NOT_FOUND: 'Convite de prestador não encontrado',
  VENDOR_INVITATION_WAS_REJECTED: 'Convite de prestador foi rejeitado',
} as const;
